# Example: Node.js service with Cloud Run deploy
name: Deploy
on:
  push:
    branches: [master]
    tags: ["v*"]
permissions:
  contents: write
  id-token: write
jobs:
  deploy:
    uses: credova/platform-workflows/.github/workflows/node-deploy.yaml@v1.0.2
    secrets: inherit
    with:
      container: true
      release: true
